### ISSUE TITLE
Practica de contratos inteligentes

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-6-contratos-inteligentes-servitlax#1]
[Practica Contrato.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-contratos-inteligentes-servitlax/files/8714886/Practica.Contrato.pdf)

**Comment by Abraham890** [comment]
calificación: 18 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
